name: Terraform AWS Deployment

on:
  pull_request:
    branches:
      - main
  workflow_dispatch:

jobs:
  terraform:
    name: 'Terraform Plan and Apply'
    runs-on: ubuntu-latest

    env:
      AWS_ACCESS_KEY_ID: 'ASIAYH6GCWRX5ALMVBCJ'
      AWS_SECRET_ACCESS_KEY: 'OFhOtXXbfwpkIsBae5ZnKExc1lyRVleDgAtrWN5J'
      AWS_DEFAULT_REGION: 'us-east-1'
      TF_VAR_region: 'us-east-1'

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v2
        with:
          terraform_version: 1.9.6

      - name: Terraform Init
        run: terraform init

      - name: Terraform Plan
        run: |
          echo "Acess key: ${{ env.AWS_ACCESS_KEY_ID }}"
          echo "Secret Acess key: ${{ env.AWS_SECRET_ACCESS_KEY }}"
          terraform plan -var="aws_access_key=${{ env.AWS_ACCESS_KEY_ID }}" -var="aws_secret_key=${{ env.AWS_SECRET_ACCESS_KEY }}" -out=plan.tfplan

      - name: Terraform Apply
        if: github.event_name == 'workflow_dispatch'
        run: terraform apply -auto-approve plan.tfplan